## Pátá lekce, návrh
1. `numpy`,
    - intro ke knihovně, jak s ní pracovat, kde, verze,
    - rozdíl datových typů, list a integer,
    - datové typy v Numpy,
    - array v Pythonu, array v numpy, základy,jejich atributy,
    - operace s maticemi, array,
    - Ufunks,
    - agregace.
    
2. Knihovna `numpy`.
    - Co je to za knihovnu, proč ji mám znát?
    - Základní datové typy, numpy array, co jsou zač, kde je jich potřeba?
    - Performance rozdíly. Agregace, výpočty, srovnávání.

### čtvrtá lekce

2. `pandas` II.,
    - file io, encoding, chybějící data,
    - kombinace datasetů, concat, append, merge, join,
    - časové řady, možná?
    - eval() a query() jako high-perf operace.

### třetí lekce

2. `pandas` I.,
    - Úvod do frameworku, proč je dobré jej ovládat, kde s ním pracovat?
    - jaké jsou základní datové typy? (Dframe, series, časové řady)
    - základní orientace, indexování,

Lekce 1: Úvod do NumPy (3 hodiny)
Úvod a motivace (20 minut)
Proč používat NumPy?
Přehled funkcí a výhod NumPy
Instalace a import NumPy
Základní datové struktury (50 minut)
NumPy pole (ndarray)
Vytváření NumPy polí (ručně, z Python seznamu, pomocí funkcí)
Atributy ndarray (tvar, velikost, dimenze)
Indexování a výběr dat (40 minut)
Přístup k prvku pomocí indexu
Řezání (slicing) a extrakce částí pole
Boolovské indexování a filtrování
Operace s NumPy poli (40 minut)
Aritmetické operace a broadcasting
Lineární algebra (skalární součin, maticový součin)
Agregační funkce (min, max, sum, mean)
Praktický příklad a cvičení (30 minut)
Demonstrační příklad: zpracování reálných dat pomocí NumPy
Individuální práce účastníků na cvičeních


## Úvod do NUMPY

---

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.QQOtOJPya2YEO6IkVBnYjQHaDV%26pid%3DApi&f=1&ipt=245c27df971ff24527ca317988f6feda8b14851ef0a889fda7d5a10d114dc5e6&ipo=images" width="300" style="margin-left:auto; margin-right:auto"/>

### Proč umět NUMPY

---

Je to univerzální knihovna pro práci **s numerickými daty** v jazyce Python.

Funkcionalita této knihovny je využívána (skrze API) v jiných knihovnách jako *Pandas&, *SciPy*, *Matplotlib*, *scikit-learn*, *scikit-image*.

Nabízí efektivní nástroje pro práci **s většími datovými strukturami**.

Usnadńuje práci se vícerozměrnými poli a maticovými datovými strukturami.

### Kde zjistit více informací

---

Dokumentaci najdeš [zde](https://numpy.org/doc/stable/index.html#).

Zdrojový kód najdeš [zde](https://github.com/numpy/numpy).

### Jak jej nainstaluji

---

Instalace knihovny obecně (doporučeno v rámci virtuálního prostředí):

In [ ]:
!pip install numpy

...nebo:

In [ ]:
!conda install numpy

<br>

Nahrávání knihovny:

In [1]:
import numpy

In [ ]:
import numpy as np

In [ ]:
from numpy import array

<br>

Používaná verze knihovny:

In [2]:
numpy.__version__

'1.24.2'

### Srovnání datových typů s a bez

---

Efektivní práce s daty si zakládá na tom, jak jsou data uložená.

Proto je zásadní tušit jak objekty zpracovává **klasický Python** a `numpy`.

In [3]:
x = 10
x = 10.0
x = "deset"

*Dynamické typování* v Pythonu vypadá jako dobrý nápad.

Přináší jistou flexibilitu a jednodušší používání.

Také s sebou ovšem nese jisté povinnosti, které by obyčejná proměnná **neměla normálně zpracovávat**.

V ukázce neukládáš pouze hodnoty, ale další doprovodné informace:
* **počet referencí**, kvůli alokaci/dealokaci paměti,
* **typ kódovací sady**,
* **velikost** následujících dat.

#### LIST v Pythonu

---

In [4]:
muj_list = [10, 10.0, "deset"]

In [5]:
datove_typy_listu = [type(hodnota) for hodnota in muj_list]

In [6]:
datove_typy_listu

[int, float, str]

<br>

Je jasné, že tento "komfort" sebou nese i svoji cenu.

Protože toho každá hodnota s sebou nese další doplňující informace (datový typ, kódování, ...).

I kdyby byly hodnoty stejného datové typu, přesto s sebou přenášejí řadu balastu.

Tomu se snaží knihovna `numpy` pomáhat.

In [7]:
from numpy import array

In [17]:
ciselne_pole = array(range(5))

In [23]:
ciselne_pole

array([0, 1, 2, 3, 4])

In [24]:
ciselne_pole.dtype

dtype('int64')

In [25]:
type(ciselne_pole)

numpy.ndarray

<br>

Na rozdíl od datového typu`list` v jazyce Python, pole v `numpy` obsahují stejný datový typ.

Pokud tomu tak není, `numpy` provede *upcast* (představ si datovou konverzi):

In [27]:
mix_desetinne_cele_hodnoty = array((1, 2, 3, 3.1416))

In [28]:
mix_desetinne_cele_hodnoty

array([1.    , 2.    , 3.    , 3.1416])

In [29]:
mix_desetinne_cele_hodnoty.dtype

dtype('float64')

<br>

Pokud potřebuješ dodržet konkrétní datový typ, použij explicitně *parametr* `dtype`:

In [33]:
jen_desetinne = array((1, 2, 3, 3.1416), dtype="int64")

In [34]:
jen_desetinne

array([1, 2, 3, 3])

<br>

`numpy` nabízí obrovskou škálu rychlých a efektivních způsobů vytváření polí a manipulace s číselnými daty v nich.

Pracuje s homogenními sekvenčnímy objekty.

#### Proč používat NUMPY

---

Pole v `numpy` jsou rychlejší a kompaktnější než `list` v Pythonu.

Pole spotřebovává **méně paměti a pohodlně se používá** (určení datových typů,..).

<br>

## Základy NUMPY

---

Protože je `numpy` postaven na jazyku C, přebírá také podobné datové typy.

Některé datové typy:
    
| Datový typ v `numpy` | Popis |
| :- | :- |
| `bool_` | boolean `True`, `False` |
| `int16` | celá čísla (bajty od -32768 do 32767) |
| `int32` | celá čísla (bajty od -2147483648 do 2147483647)) |
| `int64` | celá čísla (bajty od -9223372036854775808 to 9223372036854775807) |
| `float64` | desetinné čísla |
| `complex64` | komplexní čísla, reprezentovaná dvěma 64-bitovými dese. čísly |

<br>

Dále `numpy` poskytuje `array` objekty.

Ty slouží jako prostředky pro elegantní manipulaci s daty (znáš z `pandas`).

Základní operace pro `array`:
* **atributy**,
* **indexování**,
* **řezání**,
* **RESHAPE**,
* **JOIN** a **MERGE**.

### Vytvoření ARRAY

---

In [35]:
import numpy as np

<br>

##### Pomocí built-in sekvencí

In [54]:
muj_range = range(3)
muj_list = [3, 4, 5]
muj_tuple = (6, 7, 8)

In [55]:
muj_list_arr = np.array(muj_list)
muj_tuple_arr = np.array(muj_tuple)
muj_range_arr = np.array(muj_range)

In [56]:
muj_range_arr

array([0, 1, 2])

In [57]:
muj_list_arr

array([3, 4, 5])

In [58]:
muj_tuple_arr

array([6, 7, 8])

<br>

##### Pomocí nul

In [63]:
jen_nuly = np.zeros(5)

In [64]:
jen_nuly

array([0., 0., 0., 0., 0.])

<br>

##### Pomocí jedniček

In [68]:
jen_jednicky = np.ones(shape=(2, 3))

In [70]:
# np.ones?

In [69]:
jen_jednicky

array([[1., 1., 1.],
       [1., 1., 1.]])

<br>

##### Pomocí defaultní výplňové hodnoty

In [73]:
from math import pi

In [73]:
jen_pi = np.full(shape=(2, 2), fill_value=pi)

In [74]:
jen_pi

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

<br>

##### Pomocí rozsahů

In [76]:
interval_arr = np.arange(start=0, stop=10, step=2)

In [77]:
interval_arr

array([0, 2, 4, 6, 8])

<br>

##### Pomocí náhodných celých čísel

In [83]:
random_hodnoty = np.random.randint(low=0, high=6, size=(3, 3))

In [84]:
random_hodnoty

array([[4, 0, 5],
       [1, 1, 3],
       [0, 1, 4]])

<br>

##### Jednodimenzionální

In [38]:
m1 = np.random.randint(10, size=6)

In [39]:
m1

array([9, 2, 3, 2, 5, 8])

<br>

Tedy prakticky jednoduché pole, které se na první pohled neliší tolik od `list`.

##### Dvoudimenzionální

In [42]:
m2 = np.random.randint(10, size=(2, 3))

In [43]:
m2

array([[3, 2, 9],
       [5, 4, 3]])

<br>

Definicí oznamuješ:
1. `10`, vyber náhodné celé čísla z intervalu `0-9`,
2. vytvoř **2 řádky**,
3. .. o **3 sloupcích**.

##### Třídimenzionální

In [44]:
m3 = np.random.randint(10, size=(2, 3, 4))

In [45]:
m3

array([[[0, 8, 9, 2],
        [7, 8, 6, 6],
        [1, 9, 0, 6]],

       [[2, 2, 8, 9],
        [6, 1, 3, 5],
        [0, 8, 6, 3]]])

<br>

Definicí oznamuješ:
1. `10`, vyber náhodné celé čísla z intervalu `0-9`,
2. vytvoř **2 matice**,
3. .. o **3 řádcích**,
4. .. a **4 sloupcích**.

<br>

### Atributy pro ARRAY

---



Pokud budeš potřebovat prozkoumat existující `array`, můžeš vyzkoušet tyto atributy a metody:
1. **Dimenze**,
2. **tvar**,
3. **velikost**,
4. **datové typy**,
5. **bajtová velikost**.

##### Dimenze matice

In [92]:
m3.ndim

3

<br>

##### Tvar matice

In [86]:
m3.shape

(2, 3, 4)

<br>

##### Velikost matice

In [87]:
m3.size

24

<br>

##### Datový typ

In [93]:
m3.dtype

dtype('int64')

<br>

##### Velikost v bajtech

In [99]:
m3.nbytes

192

<br>

Jde o součin atributů **size** * **itemsize**.

<br>

### Indexování ARRAY

---



Postup vypadá podobně jako pro sekvenční datové typy v Pythonu.

Pomocí hranaté závorky a celého čísla, můžeš zpřístupnit konkrétní hodnotu/ hodnoty.

<br>

##### Jednodimenzionální

In [101]:
m1

array([9, 2, 3, 2, 5, 8])

In [102]:
m1[0]

9

In [103]:
m1[1]

2

In [104]:
m1[-1]

8

<br>

##### Dvoudimenzionální

In [106]:
m2

array([[3, 2, 9],
       [5, 4, 3]])

In [105]:
m2[0]

array([3, 2, 9])

In [108]:
m2[0][0]

3

In [109]:
m2[0, 0]

3

<br>

Pomocí indexů zpřístupníš hodnotu na konkrétní pozici a můžeš ji modifikovat:

In [110]:
m2[0, 0] = 11

In [111]:
m2

array([[11,  2,  9],
       [ 5,  4,  3]])

<br>

Dávej pozor na datové typy. Pokud budeš chtít přidat jiný datový typ:

In [112]:
m2[0, 0] = 11.11

In [113]:
m2

array([[11,  2,  9],
       [ 5,  4,  3]])

Výsledek bude na pozadí *truncatovaný*.

In [115]:
m2[0, 0] = "jedenct"

ValueError: invalid literal for int() with base 10: 'jedenct'

In [116]:
from pandas import DataFrame

In [123]:
zeme_df = DataFrame(
    data=[[11, 79], [66, 243], [196, 924]],
    index=["CZE", "UK", "Nigeria"],
    columns=["population", "surface_area"]
)

In [124]:
zeme_df

population  surface_area
CZE              11            79
UK               66           243
Nigeria         196           924

In [125]:
zeme_arr = np.array(zeme_df)

In [126]:
zeme_arr

array([[ 11,  79],
       [ 66, 243],
       [196, 924]])

<br>

### Slicing ARRAY

---



Podobně jako u zpřístupňování jednotlivých hodnot, můžeš tvořit *subarrays*.

Postup je opět velmi podobný pro *slicing* u sekvenčních hodnot.

Je doporučené udávat všechny argumenty, protože implicitní dosazování defaultních hodnot může mást uživatele.

In [127]:
zeme_arr

array([[ 11,  79],
       [ 66, 243],
       [196, 924]])

In [130]:
zeme_arr[0:2]

array([[ 11,  79],
       [ 66, 243]])

In [135]:
zeme_arr[-2:]

array([[ 66, 243],
       [196, 924]])

<br>

Pro více dimenzí, dva řádky a jeden sloupec:

In [136]:
dva_radky_jeden_sloupec = zeme_arr[:2, :1]

In [137]:
dva_radky_jeden_sloupec

array([[11],
       [66]])

In [138]:
dva_radky_jeden_sloupec = zeme_arr[::2, :1]

In [139]:
dva_radky_jeden_sloupec

array([[ 11],
       [196]])

<br>

##### **🧠 CVIČENÍ 🧠,