## Pátá lekce, návrh
1. `numpy`,
    - intro ke knihovně, jak s ní pracovat, kde, verze,
    - rozdíl datových typů, list a integer,
    - datové typy v Numpy,
    - array v Pythonu, array v numpy, základy,jejich atributy,
    - operace s maticemi, array,
    - Ufunks,
    - agregace.
    
2. Knihovna `numpy`.
    - Co je to za knihovnu, proč ji mám znát?
    - Základní datové typy, numpy array, co jsou zač, kde je jich potřeba?
    - Performance rozdíly. Agregace, výpočty, srovnávání.

Lekce 1: Úvod do NumPy (3 hodiny)
Úvod a motivace (20 minut)
Proč používat NumPy?
Přehled funkcí a výhod NumPy
Instalace a import NumPy
Základní datové struktury (50 minut)
NumPy pole (ndarray)
Vytváření NumPy polí (ručně, z Python seznamu, pomocí funkcí)
Atributy ndarray (tvar, velikost, dimenze)
Indexování a výběr dat (40 minut)
Přístup k prvku pomocí indexu
Řezání (slicing) a extrakce částí pole
Boolovské indexování a filtrování
Operace s NumPy poli (40 minut)
Aritmetické operace a broadcasting
Lineární algebra (skalární součin, maticový součin)
Agregační funkce (min, max, sum, mean)
Praktický příklad a cvičení (30 minut)
Demonstrační příklad: zpracování reálných dat pomocí NumPy
Individuální práce účastníků na cvičeních


## Úvod do NUMPY

---

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.QQOtOJPya2YEO6IkVBnYjQHaDV%26pid%3DApi&f=1&ipt=245c27df971ff24527ca317988f6feda8b14851ef0a889fda7d5a10d114dc5e6&ipo=images" width="300" style="margin-left:auto; margin-right:auto"/>

### Proč umět NUMPY

---

Je to univerzální knihovna pro práci **s numerickými daty** v jazyce Python.

Funkcionalita této knihovny je využívána (skrze API) v jiných knihovnách jako *Pandas&, *SciPy*, *Matplotlib*, *scikit-learn*, *scikit-image*.

Nabízí efektivní nástroje pro práci **s většími datovými strukturami**.

Usnadńuje práci se vícerozměrnými poli a maticovými datovými strukturami.

### Kde zjistit více informací

---

Dokumentaci najdeš [zde](https://numpy.org/doc/stable/index.html#).

Zdrojový kód najdeš [zde](https://github.com/numpy/numpy).

### Jak jej nainstaluji

---

Instalace knihovny obecně (doporučeno v rámci virtuálního prostředí):

In [ ]:
!pip install numpy

...nebo:

In [ ]:
!conda install numpy

<br>

Nahrávání knihovny:

In [1]:
import numpy

In [ ]:
import numpy as np

In [ ]:
from numpy import array

<br>

Používaná verze knihovny:

In [2]:
numpy.__version__

'1.24.2'

### Srovnání datových typů s a bez

---

Efektivní práce s daty si zakládá na tom, jak jsou data uložená.

Proto je zásadní tušit jak objekty zpracovává **klasický Python** a `numpy`.

In [3]:
x = 10
x = 10.0
x = "deset"

*Dynamické typování* v Pythonu vypadá jako dobrý nápad.

Přináší jistou flexibilitu a jednodušší používání.

Také s sebou ovšem nese jisté povinnosti, které by obyčejná proměnná **neměla normálně zpracovávat**.

V ukázce neukládáš pouze hodnoty, ale další doprovodné informace:
* **počet referencí**, kvůli alokaci/dealokaci paměti,
* **typ kódovací sady**,
* **velikost** následujících dat.

#### LIST v Pythonu

---

In [4]:
muj_list = [10, 10.0, "deset"]

In [5]:
datove_typy_listu = [type(hodnota) for hodnota in muj_list]

In [6]:
datove_typy_listu

[int, float, str]

<br>

Je jasné, že tento "komfort" sebou nese i svoji cenu.

Protože toho každá hodnota s sebou nese další doplňující informace (datový typ, kódování, ...).

I kdyby byly hodnoty stejného datové typu, přesto s sebou přenášejí řadu balastu.

Tomu se snaží knihovna `numpy` pomáhat.

In [7]:
from numpy import array

In [17]:
ciselne_pole = array(range(5))

In [23]:
ciselne_pole

array([0, 1, 2, 3, 4])

In [24]:
ciselne_pole.dtype

dtype('int64')

In [25]:
type(ciselne_pole)

numpy.ndarray

<br>

Na rozdíl od datového typu`list` v jazyce Python, pole v `numpy` obsahují stejný datový typ.

Pokud tomu tak není, `numpy` provede *upcast* (představ si datovou konverzi):

In [27]:
mix_desetinne_cele_hodnoty = array((1, 2, 3, 3.1416))

In [28]:
mix_desetinne_cele_hodnoty

array([1.    , 2.    , 3.    , 3.1416])

In [29]:
mix_desetinne_cele_hodnoty.dtype

dtype('float64')

<br>

Pokud potřebuješ dodržet konkrétní datový typ, použij explicitně *parametr* `dtype`:

In [33]:
jen_desetinne = array((1, 2, 3, 3.1416), dtype="int64")

In [34]:
jen_desetinne

array([1, 2, 3, 3])

<br>

`numpy` nabízí obrovskou škálu rychlých a efektivních způsobů vytváření polí a manipulace s číselnými daty v nich.

Pracuje s homogenními sekvenčnímy objekty.

#### Proč používat NUMPY

---

Pole v `numpy` jsou rychlejší a kompaktnější než `list` v Pythonu.

Pole spotřebovává **méně paměti a pohodlně se používá** (určení datových typů,..).

<br>

## Základy NUMPY

---

Protože je `numpy` postaven na jazyku C, přebírá také podobné datové typy.

Některé datové typy:
    
| Datový typ v `numpy` | Popis |
| :- | :- |
| `bool_` | boolean `True`, `False` |
| `int16` | celá čísla (bajty od -32768 do 32767) |
| `int32` | celá čísla (bajty od -2147483648 do 2147483647)) |
| `int64` | celá čísla (bajty od -9223372036854775808 to 9223372036854775807) |
| `float64` | desetinné čísla |
| `complex64` | komplexní čísla, reprezentovaná dvěma 64-bitovými dese. čísly |

<br>

Dále `numpy` poskytuje `array` objekty.

Ty slouží jako prostředky pro elegantní manipulaci s daty (znáš z `pandas`).

Základní operace pro `array`:
* **atributy**,
* **indexování**,
* **řezání**,
* **RESHAPE**,
* **JOIN** a **MERGE**.

### Vytvoření ARRAY

---

In [35]:
import numpy as np

<br>

##### Pomocí built-in sekvencí

In [54]:
muj_range = range(3)
muj_list = [3, 4, 5]
muj_tuple = (6, 7, 8)

In [55]:
muj_list_arr = np.array(muj_list)
muj_tuple_arr = np.array(muj_tuple)
muj_range_arr = np.array(muj_range)

In [56]:
muj_range_arr

array([0, 1, 2])

In [57]:
muj_list_arr

array([3, 4, 5])

In [58]:
muj_tuple_arr

array([6, 7, 8])

<br>

##### Pomocí nul

In [63]:
jen_nuly = np.zeros(5)

In [64]:
jen_nuly

array([0., 0., 0., 0., 0.])

<br>

##### Pomocí jedniček

In [68]:
jen_jednicky = np.ones(shape=(2, 3))

In [70]:
# np.ones?

In [69]:
jen_jednicky

array([[1., 1., 1.],
       [1., 1., 1.]])

<br>

##### Pomocí defaultní výplňové hodnoty

In [73]:
from math import pi

In [73]:
jen_pi = np.full(shape=(2, 2), fill_value=pi)

In [74]:
jen_pi

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

<br>

##### Pomocí rozsahů

In [76]:
interval_arr = np.arange(start=0, stop=10, step=2)

In [77]:
interval_arr

array([0, 2, 4, 6, 8])

<br>

##### Pomocí náhodných celých čísel

In [83]:
random_hodnoty = np.random.randint(low=0, high=6, size=(3, 3))

In [84]:
random_hodnoty

array([[4, 0, 5],
       [1, 1, 3],
       [0, 1, 4]])

<br>

##### Jednodimenzionální

In [38]:
m1 = np.random.randint(10, size=6)

In [39]:
m1

array([9, 2, 3, 2, 5, 8])

<br>

Tedy prakticky jednoduché pole, které se na první pohled neliší tolik od `list`.

##### Dvoudimenzionální

In [42]:
m2 = np.random.randint(10, size=(2, 3))

In [43]:
m2

array([[3, 2, 9],
       [5, 4, 3]])

<br>

Definicí oznamuješ:
1. `10`, vyber náhodné celé čísla z intervalu `0-9`,
2. vytvoř **2 řádky**,
3. .. o **3 sloupcích**.

##### Třídimenzionální

In [44]:
m3 = np.random.randint(10, size=(2, 3, 4))

In [45]:
m3

array([[[0, 8, 9, 2],
        [7, 8, 6, 6],
        [1, 9, 0, 6]],

       [[2, 2, 8, 9],
        [6, 1, 3, 5],
        [0, 8, 6, 3]]])

<br>

Definicí oznamuješ:
1. `10`, vyber náhodné celé čísla z intervalu `0-9`,
2. vytvoř **2 matice**,
3. .. o **3 řádcích**,
4. .. a **4 sloupcích**.

<br>

### Atributy pro ARRAY

---



Pokud budeš potřebovat prozkoumat existující `array`, můžeš vyzkoušet tyto atributy a metody:
1. **Dimenze**,
2. **tvar**,
3. **velikost**,
4. **datové typy**,
5. **bajtová velikost**.

##### Dimenze matice

In [92]:
m3.ndim

3

<br>

##### Tvar matice

In [86]:
m3.shape

(2, 3, 4)

<br>

##### Velikost matice

In [87]:
m3.size

24

<br>

##### Datový typ

In [93]:
m3.dtype

dtype('int64')

<br>

##### Velikost v bajtech

In [99]:
m3.nbytes

192

<br>

Jde o součin atributů **size** * **itemsize**.

<br>

### Indexování ARRAY

---



Postup vypadá podobně jako pro sekvenční datové typy v Pythonu.

Pomocí hranaté závorky a celého čísla, můžeš zpřístupnit konkrétní hodnotu/ hodnoty.

<br>

##### Jednodimenzionální

In [101]:
m1

array([9, 2, 3, 2, 5, 8])

In [102]:
m1[0]

9

In [103]:
m1[1]

2

In [104]:
m1[-1]

8

<br>

##### Dvoudimenzionální

In [106]:
m2

array([[3, 2, 9],
       [5, 4, 3]])

In [105]:
m2[0]

array([3, 2, 9])

In [108]:
m2[0][0]

3

In [109]:
m2[0, 0]

3

<br>

Pomocí indexů zpřístupníš hodnotu na konkrétní pozici a můžeš ji modifikovat:

In [110]:
m2[0, 0] = 11

In [111]:
m2

array([[11,  2,  9],
       [ 5,  4,  3]])

<br>

Dávej pozor na datové typy. Pokud budeš chtít přidat jiný datový typ:

In [112]:
m2[0, 0] = 11.11

In [113]:
m2

array([[11,  2,  9],
       [ 5,  4,  3]])

Výsledek bude na pozadí *truncatovaný*.

In [115]:
m2[0, 0] = "jedenct"

ValueError: invalid literal for int() with base 10: 'jedenct'

In [10]:
import numpy as np
from pandas import DataFrame

In [11]:
zeme_df = DataFrame(
    data=[[11, 79], [66, 243], [196, 924]],
    index=["CZE", "UK", "Nigeria"],
    columns=["population", "surface_area"]
)

In [12]:
zeme_df

population  surface_area
CZE              11            79
UK               66           243
Nigeria         196           924

In [13]:
zeme_arr = np.array(zeme_df)

In [14]:
zeme_arr

array([[ 11,  79],
       [ 66, 243],
       [196, 924]])

<br>

### Slicing ARRAY

---



Podobně jako u zpřístupňování jednotlivých hodnot, můžeš tvořit *subarrays*.

Postup je opět velmi podobný pro *slicing* u sekvenčních hodnot.

Je doporučené udávat všechny argumenty, protože implicitní dosazování defaultních hodnot může mást uživatele.

In [127]:
zeme_arr

array([[ 11,  79],
       [ 66, 243],
       [196, 924]])

In [130]:
zeme_arr[0:2]

array([[ 11,  79],
       [ 66, 243]])

In [135]:
zeme_arr[-2:]

array([[ 66, 243],
       [196, 924]])

<br>

Pro více dimenzí, dva řádky a jeden sloupec:

In [15]:
dva_radky_jeden_sloupec = zeme_arr[:2, :1]

In [16]:
dva_radky_jeden_sloupec

array([[11],
       [66]])

In [138]:
dva_radky_jeden_sloupec = zeme_arr[::2, :1]

In [139]:
dva_radky_jeden_sloupec

array([[ 11],
       [196]])

<br>

Pokud pracuješ se *subarrays*, používáš pohledy originální hodnoty.

V Pythonu to byla většinou kopie, původního objektu:

In [17]:
dva_radky_jeden_sloupec

array([[11],
       [66]])

In [20]:
dva_radky_jeden_sloupec[0, 0] = 13

In [21]:
dva_radky_jeden_sloupec

array([[13],
       [66]])

In [22]:
zeme_arr

array([[ 13,  79],
       [ 66, 243],
       [196, 924]])

<br>

Pokud potřebuješ přesto nachystat kopii a ponechat původní hodnoty nezměněné, vyzkoušej metodu `copy`:

In [23]:
kopie_dva_radky_jeden_sloupec = zeme_arr[:2, :1].copy()

In [ ]:
kopie_dva_radky_jeden_sloupec[0, 0] = 22

In [ ]:
kopie_dva_radky_jeden_sloupec

array([[22],
       [66]])

In [27]:
zeme_arr

array([[ 13,  79],
       [ 66, 243],
       [196, 924]])

<br>

### Přetváření ARRAY

---



Jestli budeš potřebovat změnit tvar pole nebo matice, vyzkoušej metodu `reshape`:

In [31]:
zeme_df

population  surface_area
CZE              11            79
UK               66           243
Nigeria         196           924

In [29]:
zeme_arr[0, 0] = 11

In [30]:
zeme_arr

array([[ 11,  79],
       [ 66, 243],
       [196, 924]])

Vytvoříš si jednodimenzionální pole s pomocí funkce `arange`:

In [32]:
pole = np.arange(1, 10)

In [34]:
pole

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<br>

Nachystám 2D pole, matici, pomocí metody `reshape`:

In [35]:
pole.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<br>

Pomocí metody `reshape` můžeš také měnit **řádkový vektor za sloupcový**:

In [40]:
radkovy_vektor = np.array((11, 22, 33, 44))

In [46]:
radkovy_vektor

array([11, 22, 33, 44])

In [42]:
radkovy_vektor[np.newaxis, :]

array([[11, 22, 33, 44]])

In [43]:
radkovy_vektor[:, np.newaxis]

array([[11],
       [22],
       [33],
       [44]])

In [44]:
x = np.expand_dims(radkovy_vektor, axis=1)

In [45]:
x

array([[11],
       [22],
       [33],
       [44]])

##### Ukázka

Potřebuješ převést 1D pole na 2D matici, kde budeš mít 7 hodnot na řádek.

In [54]:
np.random.seed(42)  # Nastavte seed pro reprodukovatelnost výsledků
temp_data = np.random.uniform(15, 35, size=30*7)

In [55]:
temp_data

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156,
       15.41168989, 34.39819704, 31.64885282, 19.24678221, 18.63649934,
       18.6680902 , 21.08484486, 25.49512863, 23.63890037, 20.8245828 ,
       27.23705789, 17.78987721, 20.84289297, 22.32723687, 24.12139968,
       30.70351923, 18.99347564, 25.28468877, 26.84829138, 15.92900825,
       27.15089704, 18.41048247, 16.30103186, 33.97771075, 34.31264066,
       31.16794696, 21.09227538, 16.95344228, 28.68466053, 23.80304987,
       17.4407647 , 24.9035382 , 15.68777042, 33.18640804, 20.17559963,
       28.25044569, 21.23422152, 25.40136042, 25.93420559, 18.69708911,
       34.39169256, 30.50265647, 33.78997883, 32.89654701, 26.95799958,
       33.4374847 , 16.76985004, 18.91965725, 15.90454578, 21.50660662,
       22.77354579, 20.42698064, 31.57475018, 22.13506653, 20.61869019,
       25.85392166, 17.8184845 , 31.04393962, 16.49101287, 34.73

In [56]:
temp_data.shape

(210,)

In [57]:
temp_data.ndim

1

In [58]:
tydenni_temp_data = temp_data.reshape(-1, 7)

In [59]:
tydenni_temp_data

array([[22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
        18.11989041, 16.16167224],
       [32.32352292, 27.02230023, 29.16145156, 15.41168989, 34.39819704,
        31.64885282, 19.24678221],
       [18.63649934, 18.6680902 , 21.08484486, 25.49512863, 23.63890037,
        20.8245828 , 27.23705789],
       [17.78987721, 20.84289297, 22.32723687, 24.12139968, 30.70351923,
        18.99347564, 25.28468877],
       [26.84829138, 15.92900825, 27.15089704, 18.41048247, 16.30103186,
        33.97771075, 34.31264066],
       [31.16794696, 21.09227538, 16.95344228, 28.68466053, 23.80304987,
        17.4407647 , 24.9035382 ],
       [15.68777042, 33.18640804, 20.17559963, 28.25044569, 21.23422152,
        25.40136042, 25.93420559],
       [18.69708911, 34.39169256, 30.50265647, 33.78997883, 32.89654701,
        26.95799958, 33.4374847 ],
       [16.76985004, 18.91965725, 15.90454578, 21.50660662, 22.77354579,
        20.42698064, 31.57475018],
       [22.13506653, 20.6186

<br>

### Spojování a rozdělování

---



Předchozí ukázky se vztahovaly pouze k jednomu poli, k jedné matici.

Teď uvidíš, jak můžeš kombinovat několik těchto typů objektu.

#### Spojování

Pomocí metody `concatenate` spojíš dvě pole nebo dvě matice nebo více objektů:

In [64]:
pole_1 = np.arange(1, 6)
pole_2 = np.array((6, 7, 8))

In [66]:
pole_1

array([1, 2, 3, 4, 5])

In [67]:
pole_2

array([6, 7, 8])

In [69]:
spojene_pole = np.concatenate([pole_1, pole_2])

In [70]:
spojene_pole

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
pole_2D_1 = np.random.randint(low=-15, high=15, size=(3, 2))

In [73]:
pole_2D_1

array([[  2, -14],
       [  6, -13],
       [  0,  13]])

In [74]:
pole_2D_2 = np.random.randint(low=-15, high=15, size=(5, 2))

In [75]:
pole_2D_2

array([[ -7, -12],
       [-15, -12],
       [-15,  -2],
       [  5,   0],
       [  4,   8]])

In [81]:
pole_2D_3 = np.random.randint(low=-15, high=15, size=(3, 2))

In [83]:
spojene_matice = np.concatenate([pole_2D_1, pole_2D_3], axis=1)

In [84]:
spojene_matice

array([[  2, -14,  -8,  -9],
       [  6, -13, -13,   1],
       [  0,  13, -15,   0]])

<br>

Pokud nemáš pole nebo matice stejného rozměru, je lepší pracovat s funkcemi:
1. `vstack`, vertikální napojení,
2. `hstack`, horizontální napojení,

In [85]:
pole_1

array([1, 2, 3, 4, 5])

In [86]:
pole_2D_1

array([[  2, -14],
       [  6, -13],
       [  0,  13]])

In [88]:
rozsirene_2D = np.vstack([pole_1, pole_2D_1])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [89]:
rozsirene_2D = np.vstack([pole_1[:2], pole_2D_1])

In [90]:
rozsirene_2D

array([[  1,   2],
       [  2, -14],
       [  6, -13],
       [  0,  13]])

#### Rozdělování

Opakem spojování polí a matic je rozdělování, které je možné provést pomocí funkcí:
1. `split`,
2. `hsplit`,
3. `vsplit`

In [107]:
rada_arr = np.random.randint(low=100, high=200, size=(12))

In [108]:
rada_arr

array([196, 127, 163, 196, 168, 160, 147, 118, 103, 134, 163, 148])

In [115]:
r1, r2, r3 = np.split(rada_arr, [3, 7])

In [116]:
r1, r2, r3

(array([196, 127, 163]),
 array([196, 168, 160, 147]),
 array([118, 103, 134, 163, 148]))

Takže dělení probíhá pomocí dělících indexů.

Tedy máš vždy N indexů a N + 1 polí.

In [119]:
matice = rada_arr.reshape(3, 4)

In [120]:
matice

array([[196, 127, 163, 196],
       [168, 160, 147, 118],
       [103, 134, 163, 148]])

In [124]:
leve_sl, prave_sl = np.hsplit(matice, [2])

In [125]:
leve_sl

array([[196, 127],
       [168, 160],
       [103, 134]])

In [126]:
prave_sl

array([[163, 196],
       [147, 118],
       [163, 148]])

<br>

##### **🧠 CVIČENÍ 🧠,